version: "3"

services:
  chat-back:
    image: ayeah77/nginxback01
    container_name: chat-back-container
    networks:
      - park_network
    ports:
      - "8080:8080"
    env_file:
      - .env  # .env 파일 자동 로드
    deploy:
      resources:
        limits:
          cpus: "0.4"  # 최대 CPU 50% 사용
          memory: "400M"  # 최대 400MB RAM 사용

  frontend:
    image: ayeah77/nginxfront
    container_name: chat-front-container
    networks:
      - park_network
    ports:
      - "3000:80"
    depends_on:
      - chat-back
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "400M"
    environment:
      - CI=true

  redis:
    image: redis
    container_name: redis-container
    networks:
      - park_network
    ports:
      - "6379:6379"